### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by jmchilton** [comment]
Thank you so much @nsoranzo

**Comment by bgruening** [comment]
@jmchilton @nsoranzo should we not archive this repo all together?

**Comment by martenson** [comment]
We could also "Mark this repository as archived and read-only."

edit: Ha, should've read what @bgruening said. :D

**Comment by nsoranzo** [comment]
Fine by me!

**Comment by bgruening** [comment]
I can not do this @martenson ... can you do this?

**Pull request merged**
